package net.zyexpress.site.dao;

import net.zyexpress.site.api.*;
import net.zyexpress.site.api.Package;
import org.skife.jdbi.v2.sqlobject.*;
import org.skife.jdbi.v2.sqlobject.customizers.Mapper;

import java.util.List;

public interface AddressDAO {
    @SqlUpdate("create table if not exists addressItem (id int generated by default as identity, " +
            "accountName varchar(64) not null, receiverName varchar(64) not null, phonenumber varchar(128) not null, " +
            "address varchar(128) null, postcode varchar(128) null, isDefault boolean default false)")
    void createAddressItemTable();

    @SqlUpdate("insert into addressItem (accountName, receiverName, address, phonenumber , postcode) " +
            "values(:accountName, :receiverName, :address, :phoneNumber, :postcode)")
    void addAddressItem( @BindBean Address address);

    @SqlQuery("select * from addressItem where accountName = :accountName")
    @Mapper(AddressMapper.class)
    List<Address> findByUserName(@Bind("accountName") String accountName);
}
