package net.zyexpress.site.dao;

import net.zyexpress.site.api.Package;
import net.zyexpress.site.api.PackageItemMapper;
import net.zyexpress.site.api.PackageMapper;
import org.skife.jdbi.v2.sqlobject.*;
import org.skife.jdbi.v2.sqlobject.customizers.Mapper;
import org.skife.jdbi.v2.util.IntegerMapper;

import java.util.List;

public interface PackageDAO {
    @SqlUpdate("create table if not exists package (id int generated by default as identity" +
            " (start with 10000000, increment by 1), accountName varchar(64) not null, weight double not null,"+
            " status varchar(128) not null, addressid int, idcardid int)")
    void createPackageTable();

    @SqlUpdate("create table if not exists packageItem (id int generated by default as identity, " +
            "packageId integer not null, name varchar(64) not null, brand varchar(128) not null, " +
            "specification varchar(128) null, quantity integer not null)")
    void createPackageItemTable();

    @SqlUpdate("insert into package (accountName, weight,status) values(:accountName, :weight, :status)")
    @GetGeneratedKeys
    long addPackage(@BindBean Package pkg);

    @SqlUpdate("insert into packageItem (packageId, name, brand, specification, quantity) " +
            "values(:packageId, :name, :brand, :specification, :quantity)")
    void addPackageItem(@Bind("packageId") long packageId, @BindBean Package.PackageItem packageItem);

    @SqlQuery("select id from package where accountName = :searchUserName and status = :status order by id ")
    @Mapper(IntegerMapper.class)
    List<Integer> searchPackagesByName(@Bind("searchUserName") String searchUserName,@Bind("status") String status);

    @SqlQuery("select id from package where id = :packageId order by id ")
    @Mapper(IntegerMapper.class)
    List<Integer> searchPackagesById(@Bind("packageId") long packageId);

    @SqlQuery("select id from package where status = :status order by id ")
    @Mapper(IntegerMapper.class)
    List<Integer> searchPackages(@Bind("status") String status);

    @SqlQuery("select id from package order by id ")
    @Mapper(IntegerMapper.class)
    List<Integer> searchPackagesALL();

    @SqlQuery("select id, accountName, weight,status, addressid, idcardid from package where id = :packageId")
    @Mapper(PackageMapper.class)
    Package searchPackageDetail(@Bind("packageId") int packageId);

    @SqlQuery("select name, brand, specification, quantity from packageItem where packageId = :packageId")
    @Mapper(PackageItemMapper.class)
    List<Package.PackageItem> searchPackageItems(@Bind("packageId") int packageId);

    @SqlUpdate("update package set addressid=:addressId, idcardid=:idcardId, status='paid' "+
            "where id=:packageId ")
    void editPackage(@Bind("packageId") int packageId,@Bind("addressId") int addressId,@Bind("idcardId") int idcardId);
}
