package net.zyexpress.site.dao;

import net.zyexpress.site.api.User;
import net.zyexpress.site.api.UserMapper;
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.BindBean;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.Mapper;

import java.util.List;

public interface UserDAO {
    @SqlUpdate("create table if not exists user (id int generated by default as identity, " +
            "userName varchar(32) unique not null, password varchar(128) not null, " +
            "isAdmin boolean default false, isApproved boolean default false)")
    void createUserTable();

    @SqlQuery("select * from User")
    @Mapper(UserMapper.class)
    List<User> getAll();

    @SqlQuery("select * from User where isAdmin = 'false' and isApproved = :userStatus")
    @Mapper(UserMapper.class)
    List<User> getAdminAll(@Bind("userStatus") String userStatus);

    @SqlUpdate("update User set  isApproved = 'true' where userName = :userName")
    int updateStatus(@Bind("userName") String userName);

    @SqlQuery("select * from User where userName = :userName")
    @Mapper(UserMapper.class)
    User findByUserName(@Bind("userName") String userName);

    @SqlUpdate("delete from User where userName = :userName")
    int deleteByUserName(@Bind("userName") String userName);

    @SqlUpdate("update User set password = :password where userName = :userName")
    int updatePassword(@Bind("userName") String userName, @Bind("password") String password);

    @SqlUpdate("insert into User (userName, password, isAdmin, isApproved) values " +
            "(:userName, :password, :isAdmin, :isApproved)")
    int insert(@BindBean User user);
}
