package net.zyexpress.site.dao;

import net.zyexpress.site.api.User;
import net.zyexpress.site.api.UserMapper;
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.BindBean;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.Mapper;

import java.util.List;

public interface UserDAO {
    @SqlUpdate("create table if not exists user (id int generated by default as identity, userName varchar(32) unique not null, password varchar(128) not null)")
    void createSomethingTable();

    @SqlQuery("select * from User")
    @Mapper(UserMapper.class)
    List<User> getAll();

    @SqlQuery("select * from User where userName = :userName")
    @Mapper(UserMapper.class)
    User findByUserName(@Bind("userName") String userName);

    @SqlUpdate("delete from User where userName = :userName")
    int deleteByUserName(@Bind("userName") String userName);

    @SqlUpdate("update into User set password = :password where userName = :userName")
    int updatePassword(@BindBean User person);

    @SqlUpdate("insert into User (userName, password) values (:userName, :password)")
    int insert(@BindBean User user);
}
